# Generated by Django 3.1.6 on 2021-02-17 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('userstatus', models.IntegerField(choices=[(1, 'Registration Completed'), (2, 'Account UnderReview'), (3, 'Accounts Verified')], default=1)),
                ('userrole', models.IntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Limited User')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdetail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
