# Generated by Django 3.1.6 on 2021-02-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210220_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
